CREATE TABLE Address (
  addressId INTEGER PRIMARY KEY,
  address1 VARCHAR(30) NOT NULL,
  address2 VARCHAR(30),
  landMark VARCHAR(30) NOT NULL,
  pincode VARCHAR(30) NOT NULL,
  city VARCHAR(10) NOT NULL,
  state VARCHAR(10) NOT NULL
);

CREATE SEQUENCE ADDRESS_SEQUENCE
	START WITH 1
	INCREMENT BY 1
	NOMAXVALUE
	NOCACHE
	NOCYCLE;
	